- taggit/managers.py
- tests/tests.py
Adds a `get_internal_type` method to `TaggableManager` to complement @coldmind's fix for #285 in django/django#3865
> Add get_internal_type to TaggableManager for #285

- .travis.yml
- taggit/managers.py
- tests/tests.py
- tox.ini
Addresses #284 
This brings Taggit up to speed with Django 1.8 beta 2. There may be more work to do before the final release but this should get us most of the way there.
> Django 1.8 support

- taggit/managers.py
- taggit/models.py
- tests/tests.py
Before (2 joins):
```
SELECT DISTINCT ("taggit_taggeditem"."object_id") AS "_prefetch_related_val", "taggit_tag"."id", "taggit_tag"."name", "taggit_tag"."slug" 
FROM "taggit_tag" INNER JOIN "taggit_taggeditem" ON ( "taggit_tag"."id" = "taggit_taggeditem"."tag_id" )
INNER JOIN "taggit_taggeditem" T4 ON ( "taggit_tag"."id" = T4."tag_id" ) 
WHERE ("taggit_taggeditem"."content_type_id" = %s AND T4."object_id" IN (%s))
```
After (1 join):
```
SELECT DISTINCT ("taggit_taggeditem"."object_id") AS "_prefetch_related_val", "taggit_tag"."id", "taggit_tag"."name", "taggit_tag"."slug" 
FROM "taggit_tag" INNER JOIN "taggit_taggeditem" ON ( "taggit_tag"."id" = "taggit_taggeditem"."tag_id" )
WHERE ("taggit_taggeditem"."content_type_id" = %s AND "taggit_taggeditem"."object_id" IN (%s))
```
Avoid using …
> Prefetching tags leads to 1 extra join

- docs/external_apps.txt
``django-taggit-helpers`` ([GitHub](https://github.com/mfcovington/django-taggit-helpers)/[PyPI](https://pypi.python.org/pypi/django-taggit-helpers)) makes it easier to work with admin pages of models associated with ``django-taggit`` tags by adding some helper classes:
- ``TaggitCounter``: Display (and sort by) number of Taggit tags associated with tagged items.
- ``TaggitListFilter``: Filter records by Taggit tags for the current model only. 
- ``TaggitStackedInline``: Add stacked inline for Taggit tags to admin.
- ``TaggitTabularInline``: Add tabular inline for Taggit tags to admin.
> Add 'django-taggit-helpers' to external apps list in docs

- docs/external_apps.txt
The label widget does not expose the input field so that you can add new tags. The base label widget instead shows all available tags and lets you pick between them in Django's admin interface. It presumes that you are using a managed tag list.
> Adds django-taggit-labels to external apps list

- setup.py
- taggit/models.py
Fix for non latin characters in slugs being removed and empty slugs being created. This is a resubmission of @spapas PR (see https://github.com/alex/django-taggit/issues/272) slightly modified to not have a dependency on a GPL licensed library and rebased so it applies on the current HEAD.
> Unicode tags do not have correct slugs (redux)

- docs/getting_started.txt
- taggit/managers.py
- tests/tests.py
This commit was adapted from an unmerged pull request [#263](https://github.com/alex/django-taggit/pull/263) done by [qris](https://github.com/qrisa). The following text is his original commit message:
Add case-insensitive option for tag names.
I don't think it makes sense to have tags which differ only in case. It's not even possible on MySQL because it violates the
unique constraint on tag name:
IntegrityError: (1062, "Duplicate entry 'LONDON' for key 'taggit_tag_name_6b48d50f_uniq'")
This PR adds a new setting, `TAGGIT_CASE_INSENSITIVE`, which causes existing tags to be looked up case insensitively. New
tags are added with the supplied case, which will be used from then on. The default behaviour is the same as before without
this setting.
This meets nookiepl's request on #70, and my …
> Add case-insensitive option for tag names.

- taggit/managers.py
django-taggit has a bug (#282) where it assumes that the tagged model
has a field named id which is the primary key. This isn't the case in
our database as we use a more descriptive pk/id field name. The django-taggit API lookup features fail unless this is fixed.
This commit patches the code using the fix in:
#283 and stevenday/django-taggit
> Patch django-taggit to fix #282

- CHANGELOG.txt
Also, I've added dates for versions >= 0.9.2 (taken from git tags).
> Use international ISO 8601 dates in the changelog

- taggit/models.py
[As suggested via @jezdez in #334](https://github.com/alex/django-taggit/pull/334#discussion-diff-36459222).
> for #333 - access _default_manager via TagBase class

- docs/custom_tagging.txt
- taggit/managers.py
- taggit/models.py
- tests/forms.py
- tests/migrations/0001_initial.py
- tests/models.py
- tests/tests.py
This pull request makes possible to use Django-taggit on any models with non-integer primary-key without the need to define one Through Model per tagged model (e.g. using GenericForeignKey not direct ForeignKey).
I moved the common code from GenericTaggedItemBase to a new CommonGenericTaggedItemBase class.
User may then inherit from CommonGenericTaggedItemBase to define a Through Model for custom PK while still using GenericForeignKey.
I've updated the doc to include example of a non-integer primary key and added test.
I've also included a GenericUUIDTaggedItemBase which is the same as GenericTaggedItemBase but for UUID primary-key (since it's probably the most common use case). But since it rely on Django 1.8, it's only defined for Django 1.8+
> Allows custom Through Model with GenericForeignKey

- .travis.yml
- CHANGELOG.txt
- setup.py
- tox.ini
Python 2.6 has been officially unsupported for quite some time. In
addition, no maintained versions of Django support Python 2.6. There's
no reason we should be maintaining compatibility for unmaintained and
unsecure versions of Python.
> Drop support for Python 2.6

- docs/custom_tagging.txt
- taggit/utils.py
- tests/custom_parser.py
- tests/tests.py
To provide some flexibility in parsing tag strings and creating tag strings from a list of tags, users can now provide their own functions for performing these operations.  Fixes #215.
This is per the discussion in #215.  Please let me know if there's anything else that needs to be fixed before you'll accept the PR.
> Add option to override default tag string parsing

- runtests.py
- taggit/managers.py
- taggit/utils.py
- tests/migrations/0001_initial.py
- tests/models.py
- tests/tests.py
I've fixed all deprecation warnings from all versions of Django supported by taggit, while maintaining backwards compatibility with all currently supported versions, and with all tests passing.
This involved adding some helpers for the recently renamed `field.rel.to`/`field.remote_field.model`, and changing the use of `add_lazy_relation` to `lazy_related_operation` on Django 1.9.
SQL names are quoted using the correct function now, fixing #380 and #383.
`on_delete=models.CASCADE` has been added to all ForeignKeys where it was missing, including in tests and migrations. This is backwards compatible with current code and projects, as `on_delete=models.CASCADE` was the assumed default previously.
Warnings due to different versions of unittest bundled through different version of Django have …
> Fix all deprecation warnings

- docs/custom_tagging.txt
Original code example declares `tag_string` as the argument for `comma_joiner`, however, the body of `comma_joiner` expects an iterable of `Tag` objects named `tags`.
> Fix incorrect args in custom tagging example

- .coveragerc
- .gitignore
- .travis.yml
- AUTHORS
- Makefile
- README.rst
- docs/conf.py
- requirements/test.txt
- runtests.py
- setup.cfg
- setup.py
- taggit/managers.py
- taggit/models.py
- tests/custom_parser.py
- tests/forms.py
- tests/models.py
- tests/settings.py
- tests/tests.py
- tox.ini
Small PR to start with. The main points are:
- `isort` should now be run by travis
- test results should be upload to codecov from travis
- `E302` inconsistencies fixed.
> Code and tooling improvements

- CHANGELOG.txt
- README.rst
- docs/index.txt
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs links for their .org -> .io migration for hosted projects

- taggit/managers.py
- tests/tests.py
Calling .set(..) with clear=True on an instance manager would produce an
UnboundLocalError. This behavior was introduced in
6542a702b590a5cfb91ea0de218b7f71ffd07c33. This commit fixes the issue,
and adds a separate test to test the behavior of .set(..) with
clear=True.
> Fix UnboundLocalError in _TaggableManager.set(..)

- taggit/models.py
Adding app_label to Tag and TaggedItems models for Django 1.9 compatibility. Without specifying an app_label you MUST add taggit to INSTALLED_APPS, which you may not want to do if you plan to  customize the models.
#330
> Django 1.9 app_label

- docs/admin.txt
A couple of additions to the docs for the Django admin -- explain how to include tags in fieldsets (this seemed obvious in retrospect but took me a few minutes to figure out), and provide a sample ModelAdmin that efficiently includes a list of tags in list_display.
> Address list_display and fieldsets in admin docs

- tests/tests.py
Django 1.10 now adds the "required" attribute to inputs. Handle this in
tests.
Refs #432
> Fix form tests on Django 1.10

- taggit/models.py
- tests/tests.py
This makes it possible to call `sort()` on a list of `Tag` objects in memory.
> Support __gt__ and __lt__ ordering on Tags

- AUTHORS
- taggit/managers.py
- tests/tests.py
> Check for case-insensitive duplicates when creating new tags

- taggit/managers.py
- tests/tests.py
Demonstrates and fixes bug #463, which was introduced by my last PR #461.
> Fix case-insensitive tag creation when setting to a mix of new and existing tags are used

- .travis.yml
- CHANGELOG.txt
- README.rst
- docs/index.txt
- requirements/test.txt
- setup.py
- taggit/managers.py
- taggit/models.py
- taggit/utils.py
- tests/tests.py
- tox.ini
Django 1.7 is no longer supported and has not received security updates since
2015-12-01. This avoids workarounds for potentially insecure and outdated
Django.
See table of Django supported versions:
https://www.djangoproject.com/download/#supported-versions
> Drop support for Django 1.7 and remove all workarounds

- taggit/locale/es/LC_MESSAGES/django.po
We are use to write "slug" in Spanish instead of "marquilla", that is a pretty strange word...
> Update spanish translation

- CONTRIBUTING.rst
- docs/contributing.txt
- docs/index.txt
- manage.py
- `CONTRIBUTING.rst`: this file is linked automatically
by github when opening new issues
- `docs/contributing.txt`: contribution guidelines
- `manage.py`: I added a manage.py to make it easier to run django
commands in the development environment
Regarding `manage.py`, I tried to use the `django-admin` script, but I couldn't get it working.
References issue #479
> [docs] Added contribution guidelines

- taggit/managers.py
It seems some methods, e.g., `get_extra_join_sql` in managers.py are unused, tests don't fail if this is commented out.
> Prefer decorator for total_ordering of TaggableManager

- taggit/managers.py
- tests/tests.py
Available since Python 2.7. Avoid some extra temporary lists and
function calls.
> Use set literals and set comprehension

- .travis.yml
- tox.ini
As Django master isn't fully stable, expect failures from time to time.
> Allow Travis failures for Django master

- .travis.yml
- setup.py
- taggit/managers.py
- tox.ini
Add Django 2.0 to the Travis and tox test matrix.
Add Django 2.0 to the list of trove classifiers.
Update `TaggableRel` for internal API differences of Django 2.0. Guard with a `VERSION` check where necessary.
> Add support for Django 2.0

- .travis.yml
- CHANGELOG.txt
- requirements/test.txt
- setup.py
- tox.ini
Python 3.3 is EOL and no longer receiving bug fixes, including security fixes.
Python 3.3 is not supported by the latest pytest release, which is causing test failures on Travis and with tox.
https://docs.pytest.org/en/latest/changelog.html#pytest-3-3-0-2017-11-23
> Drop support for EOL Python 3.3

- taggit/utils.py
- Reuse Django's `import_string()` utility function instead of reimplementing it. Django's function also reports more useful error messages.
- Don't bother caching the import. Python already robustly caches imports and will not reimport the same module twice. The cache is wasted.
> Simplify get_func() utility function

- taggit/forms.py
Proposed alternative fix to #505, which preserves the behaviour of the `renderer` kwarg.
`format_value` is a more suitable place for converting the value - this way we're sidestepping the need to deal with any current or future changes to Django's `render` logic.
(Unfortunately the Django <1.10 fallback code makes it pretty ugly, but hopefully that won't be there forever :-) )
> Fix TagWidget for Django 2.1

- docs/admin.txt
Many editors are configured to automatically trim trailing whitespace. By removing trailing whitespace, helps avoid inadvertent whitespace changes in future diffs.
> Trim trailing whitespace in docs/admin.txt

- .gitignore
Since pytest 3.4.0, released 2018-01-30, the directory `.pytest_cache` is created when running tests.
https://docs.pytest.org/en/latest/changelog.html#pytest-3-4-0-2018-01-30
> Add pytest cache directory to ignored files

- .travis.yml
- tox.ini
Was missed in commit 6c02219d0d94060f06cb0ff5466d8dbe2caeea30.
> Add tox environments for Python 3.7 and Django 2.1

- .travis.yml
- setup.cfg
- setup.py
- tox.ini
- Normalize configuration to a consistent list of excluded directories
- Drop isort as a requirement of setup.py
- Always lint entire project
- Lint using Python3
- In Travis, only lint the project once, not for each environment
> Improve project linting (flake8 and isort)

- taggit/managers.py
taggit/managers.py:556:60: W504 line break after binary operator
> Fix flake8 error

- docs/admin.txt
The current code throws an error:
```
(admin.E008) The value of 'fieldsets[0][1]['fields']' must be a list or tuple.
```
> Fix TaggableManager in Admin example code

- tests/tests.py
Semantics of TransactionTestCase changed after Django commit:
https://github.com/django/django/commit/b3b1d3d45fc066367f4fcacf0b06f72fcd00a9c6
Use TestCase instead which also runs tests inside a transaction.
> Fix tests to run against Django master branch

- tests/tests.py
The module already import unicode_literals. The prefix is unnecessary.
Makes the code slightly more forward compatible with Python 3 style.
> Remove u prefix from unicode strings

- taggit/managers.py
Offers no different behavior from the parent class ManyToManyRel. Remove
the indirection and instantiate ManyToManyRel instead.
> Remove unnecessary compatibility shim TaggableRel

- .travis.yml
- CHANGELOG.txt
- setup.py
- tox.ini
Django 2.2 alpha 1 was released on January 17, 2019.
https://www.djangoproject.com/weblog/2019/jan/17/django-22-alpha-1/
> Add Django 2.2a1 to the test matrix

- taggit/utils.py
The builtin has been available since Python 2.6. Makes the code more
forward compatible with Python3-only syntax.
> Replace six.next() with builtin next()

- .gitignore
- setup.cfg
> Ignore .venv for lint

- taggit/migrations/0003_taggeditem_add_unique_index.py
- taggit/models.py
- tests/migrations/0003_add_unique_indexes.py
- tests/models.py
- tests/tests.py
Prevents duplication of a`TaggedItem` on a race condition at this line:
https://github.com/jazzband/django-taggit/blob/7cea0b2d7af23d7c0e04f52d60abf3dd175cb26d/taggit/managers.py#L158-L160
The `kwargs` used in a `get_or_create` must be unique at the database level.
Fixes #349.
> Make TaggedItem unique

- CHANGELOG.txt
- taggit/models.py
- tests/tests.py
Allows placing a .most_common() query at the top level of a module.
Fixes #532
> Always evaluate .most_common() lazily

- CHANGELOG.rst
- taggit/models.py
- tests/migrations/0001_initial.py
- tests/models.py
- tests/tests.py
`ItemBase.tags_for()` was moved to `TaggedItemBase` in 998ef2f as part of a fix to avoid direct reference to the default `Tag` model. The change made use of `ItemBase.tag_model()` instead so moving `ItemBase.tags_for()` was unnecessary and makes subclassing `ItemBase` more difficult.
Fixes #101.
> Moved TaggedItemBase.tags_for() to ItemBase.

- .travis.yml
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
> Travis container based environment is deprecated

- .travis.yml
- CHANGELOG.rst
- setup.py
- tox.ini
Will reduce testing time and resources.
> Remove support for end-of-life Django 2.0

- docs/custom_tagging.rst
I changed some ForeignKey declarations in `docs/custom_tagging.rst`.
They didn't have the mandatory `on_delete` argument.
> Fixed ForeignKey.on_delete

- taggit/views.py
Unnecessary since dropping support for Python 2 in
828e5481069d51a02ceb724bacbae371b8fdd1f0.
> Remove Unnecessary str() call

- README.rst
Just let readthedocs redirect to the default.
> Remove 'en/latest/' from URL

- taggit/managers.py
- taggit/models.py
- tests/tests.py
Using .__class__ was necessary to support Python 2 old style classes. In
Python 3, all classes are new style.
> Replace .__class__ with type()

- taggit/models.py
There is a small typo in taggit/models.py.
Should read `opportunistic` rather than `oportunistic`.
> docs: Fix simple typo, oportunistic -> opportunistic

- CHANGELOG.rst
- taggit/migrations/0001_initial.py
- taggit/models.py
Allows for using the name in a sentence. For uses that are a header,
title, or at the beginning of a sentence, a text transform can be used.
> Change case of verbose_name attributes to lowercase

- CHANGELOG.rst
- docs/conf.py
- taggit/__init__.py
I'm not sure who is the release manager for this lib, and I don't see any "autorelease on tag" infrastructure, so I'm going to ping both @auvipy and @jdufresne on this (apologies in advance to the one who didn't need to get pinged here)
> Prepare for the next release

- docs/custom_tagging.rst
If you are using custom models, having 'taggit' in the installed apps will create database tables you do not need.
> Add tip for using custom models

- setup.cfg
- taggit/models.py
- tests/tests.py
- tests/views.py
- tox.ini
isort now has builtin support for black through its "profiles" feature.
https://timothycrosley.github.io/isort/docs/configuration/profiles/#black
>  Simplify isort config using 'profile = black'

- tests/migrations/0002_auto_20200214_1129.py
- tests/tests.py
Hi,
While running jobs on travis-ci, I encountered that jobs on TOXENV=black were failing. I looked into it and came up with the possible fix. It appears the fix is ready to review and merge, so kindly have a look to it.
Jobs can be verified by: https://travis-ci.com/github/kishorkunal-raj/django-taggit/builds/190199247
Thanks!
Regards 
Kishor Kunal Raj
> Fixing issues on TOXENV=black as jobs not running on intel

- taggit/apps.py
Django 3.2 [introduces](https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys) a change that wants `default_auto_field` to be set on an AppConfig, or else the `DEFAULT_AUTO_FIELD` setting set. Otherwise a warning is generated.
Added the setting to `TaggitAppConfig` in order to keep the existing behaviour.
Fixes #717
> Add default_auto_field to TaggitAppConfig

- README.rst
- docs/faq.rst
- docs/index.rst
This removes the (basically unused) mailinlist form the readme, instead pointing people to open up a GH issue.
I also add an FAQ page for the docs, though for now I only have two simple questions answered.
> Some slight documentation tweaks

- taggit/__init__.py
I missed this step when preparing the release, causing the release step to fail upon tagging.
> Bump the taggit version number to 1.4.0

- tox.ini
Python 3.5 is no longer supported. Refs 7cea0b2d7af23d7c0e04f52d60abf3dd175cb26d
> Update black target to Python 3.6

- CHANGELOG.rst
- taggit/__init__.py
This is a bit of a bugfix release to get the most recent version of the library in a working state again. (This also fixes a mistaken timestamp in the changelog)
> Prepare Release 1.5.1

- CHANGELOG.rst
- docs/forms.rst
- taggit/forms.py
- tests/test_forms.py
Thanks to #749  for the initial report and pointing to a potential fix.
Also tries to address #752 by adding a link to Django docs.
> Fix TagField.has_changed for empty values 

- CHANGELOG.rst
- taggit/__init__.py
This is version 2.0.0 because of an API compatibility change.
> Prepare release

- .github/workflows/test.yml
- requirements/docs.txt
I've noticed that the documentation build was broken after looking into the 2.0.0 release and found it to be related to https://github.com/sphinx-doc/sphinx/issues/9811, one of the many incarnations of docutils 0.18 containing breaking changes for Sphinx. This pins to docutils<0.18 to work around it for now.
I've also took the liberty to enable [pull request building for the docs via Read The Docs](https://docs.readthedocs.io/en/stable/pull-requests.html), so we see build issues earlier, see the pull request jobs/checks below. The preview is here: https://django-taggit--768.org.readthedocs.build/en/768/
> Fix doc build and workflow job name.

- CHANGELOG.rst
- setup.cfg
- taggit/managers.py
- tox.ini
The `where_class` argument to the private `get_extra_restriction()` was [changed](https://docs.djangoproject.com/en/4.0/releases/4.0/#miscellaneous) in Django 4.0.
A simple change is to remove the `where_class` argument [here](https://github.com/jazzband/django-taggit/blob/4042b8562d72b8b65581de01277e8b37514cf514/taggit/managers.py#L669). But that breaks taggit on lower versions of django.
To fix this, I added a shim that checks the django version and uses the correct function. 
I have no idea if this is the best way to fix this, but the tests pass 🤷‍♂️ 
Relevant issue: #776 
Note that this PR has a commit from #777 too.
> Fix Django 4 compatibility issues

- tests/tests.py
The old behaviour of assertQuerysetEqual automatically calling repr is deprecated in Django 3.2 https://docs.djangoproject.com/en/4.0/releases/3.2/#id3 and dropped in Django 4.1.
> Set transform=repr on assertQuerysetEqual (Dj4.1 compatibility)

- taggit/managers.py
- tests/tests.py
In https://github.com/django/django/commit/a697424969f7f464bf6492b09a6cdac135499e02 / https://github.com/django/django/pull/14750, Django has introduced two new cached properties `path_infos` and `reverse_path_infos` to be used in preference to the `get_path_info()` and `get_reverse_path_info()` methods when not passing a `filtered_relation` argument.
TaggableManager is patching these methods, so to avoid Django bypassing them (specifically in `django.db.query.Query.names_to_path`) it needs to provide these cached properties too.
For additional bonus points, we also update TaggableManager's `_get_mm_case_path_info` and `_get_gfk_case_path_info` methods to make use of the new cached properties where available.
This (along with #791, incorporated here) gets the test suite passing again on …
> Handle path_infos / reverse_path_infos cached properties (Dj4.1 compatibility)

- docs/custom_tagging.rst
`django.utils.translation.ugettext_lazy` was deprecated in Django 3.0 and removed in Django 4.0 in favor of `django.utils.translation.gettext_lazy`.
> Docs: replace deprecated/removed `django.utils.translation.ugettext_lazy`

- CHANGELOG.rst
- taggit/managers.py
- tests/test_models.py
- tests/test_serializers.py
This mimics the behaviour of Django's `ManyRelatedManager`
Take `test_returns_new_data_after_update`. It emulates the behaviour of Django-rest-framework's UpdateModelMixin.
If I did any `prefetch_related` on my QuerySet, the resulting data still uses the prefetched results instead of the updated data.
> Clear prefetch cache on tag updates

- docs/faq.rst
- taggit/managers.py
- tests/tests.py
There are small typos in:
- docs/faq.rst
- taggit/managers.py
- tests/tests.py
Fixes:
- Should read `stored` rather than `storred`.
- Should read `intermediary` rather than `intermeidary`.
- Should read `function` rather than `funtion`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- docs/getting_started.rst
Right now settings list looks incorrect and the PR fixes that:
> Fix settings list markup in the getting started docs.

- CHANGELOG.rst
- taggit/serializers.py
- tests/test_serializers.py
This is a very tricky change, and I expect some issues once people begin using this in earnest. But it is closer to where we want to be, and the main functionality is being tested. 
This change is motivated by documentation tools not properly identifying this field as a `ListField`.
This also includes ome documentation tweaks in the changelog
Thanks to @brittandeyoung for the initial PR
Fixes #828
> Make TagListSerializerField subclass ListField

- .github/workflows/test.yml
- CHANGELOG.rst
- taggit/managers.py
- taggit/migrations/0001_initial.py
- taggit/migrations/0002_auto_20150616_2121.py
- taggit/migrations/0003_taggeditem_add_unique_index.py
- taggit/migrations/0004_alter_taggeditem_content_type_alter_taggeditem_tag.py
- taggit/migrations/0005_auto_20220424_2025.py
- tests/migrations/0001_initial.py
- tests/migrations/0002_auto_20200214_1129.py
- tests/migrations/0003_auto_20210310_0918.py
- tests/migrations/0004_auto_20210619_0826.py
- tests/migrations/0005_auto_20210713_2301.py
- tests/serializers.py
- tests/tests.py
- tox.ini
This is pulling in a lot of work from #852 and #848
> Update Django Support

- CHANGELOG.rst
- CONTRIBUTING.rst
- setup.cfg
This just tags the requirements properly.
@jezdez I think we want to yank 5.0.0 (after I release 5.0.!), just because Django 3.2 is an LTS release so until mid-2024. Is there a process that would allow me to do yanking on Pypi?
> Prepare v5.0.1

- .readthedocs.yml
- CONTRIBUTING.rst
- docs/conf.py
- docs/index.rst
- taggit/__init__.py
This is an attempt to get the readthedocs.io builds working again
> Add a readthedocs configuration file

- AUTHORS
- CHANGELOG.rst
- setup.cfg
- taggit/managers.py
- tests/test_models.py
- tests/tests.py
This is based off of work done by @steverecio on #871 
This doesn't cause a change in query count.
@steverecio would you mind looking over this? And do you want to be placed in the `AUTHORS` file? I appreciate you digging through this, your PR was very helpful and helped me to understand what needed to be done to get this working.
> Default tag ordering to the primary key

- CHANGELOG.rst
- setup.cfg
- tox.ini
#894 
Adds support for Django 5.0 for python versions >= 3.10.  
Django 5.0 only supports python 3.10, 3.11 and 3.12 currently - [Django Compatibility]( https://docs.djangoproject.com/en/5.0/releases/5.0/#python-compatibility
)
[Django release Notes](https://docs.djangoproject.com/en/5.0/releases/5.0/)
> 894 - Add django 5.0 Support

- CHANGELOG.rst
- taggit/management/commands/remove_orphaned_tags.py
- tests/test_remove_orphaned_tags.py
- This PR handles removing orphaned tags
- This is connected to PR #904 and pertains to issue #682. 
- I branched this off of my #904 branch since they were related but I can do a fresh PR if needed.
- `CHANGELOG.rst`
- `taggit/management/commands/remove_orphaned_tags.py`
- Pull code down locally
- `pip install -e location_of_your_app/django-taggit`
- run `python manage.py remove_orphaned_tags` inside of your sample_app
- https://docs.djangoproject.com/en/5.0/howto/custom-management-commands/
https://www.loom.com/share/0c2b3f0b2dab4d7da9d2943f1520e12e?sid=98d050f0-3046-4aee-b2ec-78945b2a5408
> [#682] - Remove Orphaned Tags

- CHANGELOG.rst
- MANIFEST.in
> Exclude docs, tests, and the sample project from the package

- CHANGELOG.rst
- taggit/admin.py
- taggit/management/commands/remove_orphaned_tags.py
- taggit/models.py
We have a management command to remove orphaned tags but I also wanted to add functionality to do it as an admin action from the drop down list.
- https://www.loom.com/share/3cd37182c652493997bbfd92f3eab5f9?sid=78dc947a-102c-4f53-800e-368264ac039f
> Add an admin action to remove orphaned tags

- .github/workflows/release.yml
- .github/workflows/test.yml
- CHANGELOG.rst
- docs/index.rst
- setup.cfg
- taggit/__init__.py
- tox.ini
Overview:
This PR is mainly for cleanup. Now that Python 3.8 has officially reached EoL, it is time to remove support for that version.
This refers to #900
Updates:
These 2 are probably the most important for review since they handle CI/CD workflows
- `.github/workflows/release.yml`
- `.github/workflows/test.yml`
########################
- `CHANGELOG.rst`
- `docs/index.rst`
- `setup.cfg`
- `taggit/__init__.py`
- `tox.ini`
> Removing 3.8

- CHANGELOG.rst
- taggit/admin.py
- tests/test_admin.py
Querystrings are preventing the tags from merging, because `get_full_path()` in the redirect preserves querystrings.
**Steps to reproduce**
1. Load the admin area > Taggit > Tags
2. Sort by `slug` so that the path is `/admin/taggit/tag/?o=2.1` (with querystring)
3. Select two tags, eg: "Adventure" and "Anthology, then action "Merge selected tags"
**Result**
Because the resulting path is `/admin/taggit/tag/?o=2.1merge-tags/` you stay on the listing page.
This also affects paging querystrings.
**Fix**
Use `request.path` instead of `request.get_full_path()`.
> Fix bug with merge form action when querystring is present.

- taggit/models.py
- tests/test_models.py
- tox.ini
> Fix test suite failing if unidecode is installed
