jazzband/django-taggit

- taggit/managers.py
In response to https://github.com/alex/django-taggit/issues/321
> Implemented user jcalazan's fix for an issue, and ran tests, closes #321

- taggit/migrations/0002_auto_20150616_2121.py
- taggit/models.py
https://github.com/alex/django-taggit/issues/318
> improving query performance (issues #318)

- docs/admin.txt
The previous link was resulting in a 404.
> Update documentation link to latest Django stable release

- .travis.yml
- taggit/managers.py
- tox.ini
Continued from https://github.com/alex/django-taggit/issues/329
> Django 1.9 support

- taggit/managers.py
- tests/tests.py
Rebased version of #361/#362
Closes #362
Closes #361
Closes #360
> Django 1.9 fixes

- tests/tests.py
> removed django 1.3 check from test

- docs/api.txt
- taggit/managers.py
- tests/tests.py
Rebase of https://github.com/alex/django-taggit/pull/239
> add the min_count parameter to managers.most_common function

- docs/external_apps.txt
Ordered alphabetically
HTTPS links
Added django-taggit-serializer
> external_apps.txt improvements

- runtests.py
- setup.cfg
- setup.py
- tests/forms.py
- tests/tests.py
- tox.ini
delete unused code as part of this
> introduce isort and flake8 in the CI

- docs/external_apps.txt
> [docs] Fixed links to external apps

- .travis.yml
- tests/settings.py
- tox.ini
Adjust MIDDLEWARE/MIDDLEWARE_CLASSES with a conditional based on the version
> Add Django master to the test matrix

- tests/settings.py
Remove unnecessary or default values from settings.py. Makes the file shorter and slightly easier to read and maintain.
> Simplify test settings.py

- tests/tests.py
I searched, and this seems like one possible way to test that's something has been saved or not.
> Add missing tests for required primary key

- .gitignore
- .travis.yml
- Makefile
- manage.py
- requirements/test.txt
- tests/tests.py
- tox.ini
- Use more descriptive label "django" not just a number
- Use builtin dependency support
- Pass {posargs} to pytest
- Add minversion
> Clean up tox.ini

- tests/tests.py
- tests/urls.py
- tests/views.py
- Put all TagModelTestCase together
- Move form-test-only functions to TaggableFormTestCase
- Move view to views.py
> Organize tests

- AUTHORS
https://github.com/alex/django-taggit/commits?author=jdufresne
> Add myself to the authors list

- CHANGELOG.txt
- README.rst
- docs/contributing.txt
- docs/external_apps.txt
- setup.py
- taggit/managers.py
Refs https://github.com/jazzband/roadies/issues/126
> Update all GitHub URLs to Jazzband

- README.rst
Refs https://github.com/jazzband/roadies/issues/126
> Add Jazzband badge to README.rst

- taggit/views.py
https://docs.djangoproject.com/en/dev/ref/class-based-views/mixins-multiple-object/#django.views.generic.list.MultipleObjectMixin.model
> Correct view arg from ContentType instance to Model instance

- CHANGELOG.txt
- taggit/managers.py
- tests/tests.py
Fixues issue #576 
I'm looking into writing tests for this, but I'm having trouble figuring out how to deterministic-ally test a race condition.
> Fix race condition in TaggableManager

- taggit/managers.py
Already included by the parent class.
> Remove unnecessary total_ordering use

- CONTRIBUTING.rst
One-liner might be easy to use.
> Use one-liner tox command for style checking

- docs/conf.py
- setup.cfg
These tools ignore common directories by default.
> Move close to flake8/isort defaults

- tests/test_utils.py
I've added two test to improve coverage percentage.
> Additional tests for split_strip function

- taggit/models.py
- tests/migrations/0001_initial.py
- tests/models.py
- tests/tests.py
Addresses #622. Let me know if I'm overlooking anything or need more/different test coverage.
> Add fix and tests for generic tagging on proxy models

- taggit/managers.py
Hello @jdufresne!
Closes https://github.com/jazzband/django-taggit/issues/624
> Change deprecated private attribute to support Django>=1.11

- taggit/forms.py
* Extract `format_value` method to mixin to allow using with other types of widgets.
* Add `TextareaTagWidget`
> Extract widget method to mixin and add TextareaTagWidget

- docs/getting_started.rst
> docs: update Getting Started text phrasing

- .travis.yml
> Remove xenial from .travis.yml

- .travis.yml
- tox.ini
> Test Django 2.2 with Python 3.8

- taggit/models.py
> Fix simple typo: concurrecny -> concurrency

- docs/external_apps.rst
> django-tagging-bulk external application

- CHANGELOG.rst
(Just did some rewording and labelling of the release)
> Prepare 1.4.0 release

- docs/getting_started.rst
Found a spelling mistake in the docs, figured I'd correct it and send you over a quick PR. Have a great day!
> Fixed small spelling mistake

- taggit/__init__.py
Django 3.2 deprecated default_app_config.
https://docs.djangoproject.com/en/3.2/releases/3.2/#automatic-appconfig-discovery
> Use default app config discovery

- taggit/__init__.py
Always forgetting this step for building out releases....
> Bump the version constant

- docs/faq.rst
This is in response to a question we got in the issue tracker.
> Add question to FAQ

- docs/serializers.rst
Without it DRF raises error (since 3.3.0)
> Update serializer with explicit fields value

- CHANGELOG.rst
- docs/faq.rst
- taggit/__init__.py
This also includes some extra documentation for factory_boy usage that I had written up last month but had not sent in.
> Prepare Django Taggit 2.1.0 Release

- CHANGELOG.rst
- CONTRIBUTING.rst
- taggit/__init__.py
added some instructions for myself to make sure I do all of this in the right order...
> Prepare the release of Version 3.0.0

- CHANGELOG.rst
- CONTRIBUTING.rst
- taggit/__init__.py
This also updates some of the contributing docs
> Prepare 3.1.0 release

- CHANGELOG.rst
> Fix index_together CHANGELOG note

- CHANGELOG.rst
- MANIFEST.in
This is trying to get a file to show up in the final bundle
> Fix missing template file in packaging
